export const ATTENDANCE_GET_REQUEST = "ATTENDANCE_GET_REQUEST";
export const ATTENDANCE_GET_SUCCESS = "ATTENDANCE_GET_SUCCESS";
export const ATTENDANCE_GET_FAIL = "ATTENDANCE_GET_FAIL";

export const ATTENDANCE_MARK_REQUEST = "ATTENDANCE_MARK_REQUEST";
export const ATTENDANCE_MARK_SUCCESS = "ATTENDANCE_MARK_SUCCESS";
export const ATTENDANCE_MARK_FAIL = "ATTENDANCE_MARK_FAIL";
