export const BILLING_GET_REQUEST = "BILLING_GET_REQUEST";
export const BILLING_GET_SUCCESS = "BILLING_GET_SUCCESS";
export const BILLING_GET_FAIL = "BILLING_GET_FAIL";


export const BILLING_HISTORY_REQUEST = "BILLING_HISTORY_REQUEST";
export const BILLING_HISTORY_SUCCESS = "BILLING_HISTORY_SUCCESS";
export const BILLING_HISTORY_FAIL = "BILLING_HISTORY_FAIL";