export const ENROLLMENT_REQUEST = "ENROLLMENT_REQUEST";
export const ENROLLMENT_SUCCESS = "ENROLLMENT_SUCCESS";
export const ENROLLMENT_FAIL = "ENROLLMENT_FAIL";

export const ENROLLMENT_DETAILS_REQUEST = "ENROLLMENT_DETAILS_REQUEST ";
export const ENROLLMENT_DETAILS_SUCCESS = "ENROLLMENT_DETAILS_SUCCESS ";
export const ENROLLMENT_DETAILS_FAIL = "ENROLLMENT_DETAILS_FAIL ";